name: qwen_anki_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - git
  - gcc_linux-64  # Ignored on Windows automatically
  - ffmpeg
  - sox
  - libsndfile
  - tk
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - pip:
    - ollama
    - genanki
    - rich
    - EbookLib
    - soundfile
    - pydub
    - customtkinter
    - pillow
